Repository v2land/v2land-redstone, pull requests merged in 2018-02, with the labels that each got.

#54 Create the event/news when the client is a manager or admin.
  api/controllers/EventController.js
  api/policies/isAdmin.js
  api/policies/isLoggedIn.js
  api/policies/isManager.js
  api/responses/serverError.js
  config/policies.js
Labels: api, enhancement

#57 fix spelling mistakes
  api/controllers/ClientController.js
  config/routes.js
Labels: bug

#56 Add update password api
  api/controllers/AuthController.js
  api/controllers/ClientController.js
  api/controllers/EventController.js
  api/controllers/NewsController.js
  api/controllers/UploadController.js
  api/models/Auth.js
  api/models/Client.js
  api/models/News.js
  api/models/Record.js
  api/services/AuthService.js
  api/services/ClientService.js
  api/services/SQLService.js
  config/policies.js
  config/routes.js
  docs/api/Client.md
  tests/integration/controllers/ClientController.test.js
  tests/integration/controllers/EventController.test.js
  tests/integration/controllers/NewsController.test.js
Labels: feature
